// TrainDatabase.js

export const trainRoutes = [
    {
      trainNumber: "12001",
      trainName: "Shatabdi Express",
      from: "Delhi",
      to: "Amritsar",
      departureTime: "06:00 AM",
      arrivalTime: "12:00 PM",
      stops: ["Delhi", "Ambala", "Ludhiana", "Jalandhar", "Amritsar"],
      duration: "6h 0m",
    },
    {
      trainNumber: "12245",
      trainName: "Duronto Express",
      from: "Mumbai",
      to: "Kolkata",
      departureTime: "05:30 PM",
      arrivalTime: "08:00 AM",
      stops: ["Mumbai", "Nagpur", "Raipur", "Ranchi", "Kolkata"],
      duration: "14h 30m",
    },
    {
      trainNumber: "15626",
      trainName: "Agartala Express",
      from: "Agartala",
      to: "Guwahati",
      departureTime: "07:30 AM",
      arrivalTime: "06:45 PM",
      stops: ["Agartala", "Dharmanagar", "Karimganj", "Lumding", "Guwahati"],
      duration: "11h 15m",
    },
    {
      trainNumber: "15695",
      trainName: "Tripura Sundari Express",
      from: "Agartala",
      to: "Delhi",
      departureTime: "02:30 PM",
      arrivalTime: "05:45 PM",
      stops: ["Agartala", "Dharmanagar", "Guwahati", "New Jalpaiguri", "Delhi"],
      duration: "51h 15m",
    },
    {
      trainNumber: "12504",
      trainName: "Guwahati Express",
      from: "Agartala",
      to: "Bengaluru",
      departureTime: "09:00 AM",
      arrivalTime: "03:30 PM",
      stops: ["Agartala", "Lumding", "Howrah", "Chennai", "Bengaluru"],
      duration: "54h 30m",
    },
    {
      trainNumber: "15668",
      trainName: "Nagaland Express",
      from: "Agartala",
      to: "Dimapur",
      departureTime: "06:00 AM",
      arrivalTime: "08:00 PM",
      stops: ["Agartala", "Karimganj", "Lumding", "Dimapur"],
      duration: "14h 0m",
    },
    {
      trainNumber: "13282",
      trainName: "Agartala Patna Express",
      from: "Agartala",
      to: "Patna",
      departureTime: "10:30 AM",
      arrivalTime: "08:45 PM",
      stops: ["Agartala", "Lumding", "New Jalpaiguri", "Katihar", "Patna"],
      duration: "34h 15m",
    },
    {
      trainNumber: "15909",
      trainName: "Avadh Assam Express",
      from: "Guwahati",
      to: "Lalgarh",
      departureTime: "07:30 AM",
      arrivalTime: "06:45 AM",
      stops: ["Guwahati", "Katihar", "Gorakhpur", "Delhi", "Lalgarh"],
      duration: "47h 15m",
    },
    {
      trainNumber: "15644",
      trainName: "Kamakhya Express",
      from: "Guwahati",
      to: "Puri",
      departureTime: "05:30 PM",
      arrivalTime: "11:45 AM",
      stops: ["Guwahati", "Kolkata", "Kharagpur", "Bhubaneswar", "Puri"],
      duration: "18h 15m",
    },
    {
      trainNumber: "12507",
      trainName: "Arunachal Express",
      from: "Agartala",
      to: "Naharlagun",
      departureTime: "08:00 AM",
      arrivalTime: "09:45 AM",
      stops: ["Agartala", "Lumding", "Guwahati", "Rangiya", "Naharlagun"],
      duration: "25h 45m",
    },
    {
      trainNumber: "13174",
      trainName: "Kanchenjunga Express",
      from: "Agartala",
      to: "Sealdah",
      departureTime: "03:00 PM",
      arrivalTime: "05:30 AM",
      stops: ["Agartala", "Guwahati", "New Jalpaiguri", "Malda Town", "Sealdah"],
      duration: "38h 30m",
    },
    {
      trainNumber: "22502",
      trainName: "New Tinsukia Rajdhani",
      from: "Guwahati",
      to: "Delhi",
      departureTime: "09:20 AM",
      arrivalTime: "01:00 PM",
      stops: ["Guwahati", "Katihar", "Patna", "Varanasi", "Delhi"],
      duration: "27h 40m",
    },
    {
      trainNumber: "15960",
      trainName: "Kamrup Express",
      from: "Dibrugarh",
      to: "Howrah",
      departureTime: "06:30 PM",
      arrivalTime: "07:00 AM",
      stops: ["Dibrugarh", "Guwahati", "New Jalpaiguri", "Malda Town", "Howrah"],
      duration: "36h 30m",
    },
    {
      trainNumber: "15651",
      trainName: "Lohit Express",
      from: "Guwahati",
      to: "Jammu Tawi",
      departureTime: "10:45 AM",
      arrivalTime: "04:00 PM",
      stops: ["Guwahati", "Katihar", "Lucknow", "Ludhiana", "Jammu Tawi"],
      duration: "57h 15m",
    },
  ];
  
  