// TrainDatabase.js

export const trainRoutes = [
  {
    trainNumber: "12001",
    trainName: "Shatabdi Express",
    from: "Delhi",
    to: "Amritsar",
    departureTime: "06:00 AM",
    arrivalTime: "12:00 PM",
    stops: [
      { name: "Delhi", arrivalTime: "06:00 AM", departureTime: "06:00 AM" },
      { name: "Ambala", arrivalTime: "08:00 AM", departureTime: "08:15 AM" },
      { name: "Ludhiana", arrivalTime: "09:30 AM", departureTime: "09:45 AM" },
      { name: "Jalandhar", arrivalTime: "10:30 AM", departureTime: "10:45 AM" },
      { name: "Amritsar", arrivalTime: "12:00 PM", departureTime: "12:00 PM" },
    ],
    duration: "6h 0m",
  },
  {
    trainNumber: "12245",
    trainName: "Duronto Express",
    from: "Mumbai",
    to: "Kolkata",
    departureTime: "05:30 PM",
    arrivalTime: "08:00 AM",
    stops: [
      { name: "Mumbai", arrivalTime: "05:30 PM", departureTime: "05:30 PM" },
      { name: "Nagpur", arrivalTime: "10:00 PM", departureTime: "10:15 PM" },
      { name: "Raipur", arrivalTime: "02:00 AM", departureTime: "02:15 AM" },
      { name: "Ranchi", arrivalTime: "06:00 AM", departureTime: "06:15 AM" },
      { name: "Kolkata", arrivalTime: "08:00 AM", departureTime: "08:00 AM" },
    ],
    duration: "14h 30m",
  },
  {
    trainNumber: "15626",
    trainName: "Agartala Express",
    from: "Agartala",
    to: "Guwahati",
    departureTime: "07:30 AM",
    arrivalTime: "06:45 PM",
    stops: [
      { name: "Agartala", arrivalTime: "07:30 AM", departureTime: "07:30 AM" },
      { name: "Dharmanagar", arrivalTime: "09:00 AM", departureTime: "09:15 AM" },
      { name: "Karimganj", arrivalTime: "10:30 AM", departureTime: "10:45 AM" },
      { name: "Lumding", arrivalTime: "03:00 PM", departureTime: "03:15 PM" },
      { name: "Guwahati", arrivalTime: "06:45 PM", departureTime: "06:45 PM" },
    ],
    duration: "11h 15m",
  },
  {
    trainNumber: "15695",
    trainName: "Tripura Sundari Express",
    from: "Agartala",
    to: "Delhi",
    departureTime: "02:30 PM",
    arrivalTime: "05:45 PM",
    stops: [
      { name: "Agartala", arrivalTime: "02:30 PM", departureTime: "02:30 PM" },
      { name: "Dharmanagar", arrivalTime: "03:00 PM", departureTime: "03:15 PM" },
      { name: "Guwahati", arrivalTime: "06:00 PM", departureTime: "06:15 PM" },
      { name: "New Jalpaiguri", arrivalTime: "10:00 PM", departureTime: "10:15 PM" },
      { name: "Delhi", arrivalTime: "05:45 PM", departureTime: "05:45 PM" },
    ],
    duration: "51h 15m",
  },
  {
    trainNumber: "12504",
    trainName: "Guwahati Express",
    from: "Agartala",
    to: "Bengaluru",
    departureTime: "09:00 AM",
    arrivalTime: "03:30 PM",
    stops: [
      { name: "Agartala", arrivalTime: "09:00 AM", departureTime: "09:00 AM" },
      { name: "Lumding", arrivalTime: "11:00 AM", departureTime: "11:15 AM" },
      { name: "Howrah", arrivalTime: "09:00 PM", departureTime: "09:15 PM" },
      { name: "Chennai", arrivalTime: "01:00 AM", departureTime: "01:15 AM" },
      { name: "Bengaluru", arrivalTime: "03:30 PM", departureTime: "03:30 PM" },
    ],
    duration: "54h 30m",
  },
  {
    trainNumber: "12345",
    trainName: "Agartala Fast Express",
    from: "Agartala",
    to: "Kolkata",
    departureTime: "08:00 AM",
    arrivalTime: "10:00 PM",
    stops: [
      { name: "Agartala", arrivalTime: "08:00 AM", departureTime: "08:00 AM" },
      { name: "Silchar", arrivalTime: "09:30 AM", departureTime: "09:45 AM" },
      { name: "Guwahati", arrivalTime: "12:00 PM", departureTime: "12:15 PM" },
      { name: "New Jalpaiguri", arrivalTime: "04:30 PM", departureTime: "04:45 PM" },
      { name: "Kolkata", arrivalTime: "10:00 PM", departureTime: "10:00 PM" },
    ],
    duration: "14h 0m",
  },
  {
    trainNumber: "13456",
    trainName: "Agartala Superfast",
    from: "Agartala",
    to: "Chennai",
    departureTime: "05:00 AM",
    arrivalTime: "11:00 PM",
    stops: [
      { name: "Agartala", arrivalTime: "05:00 AM", departureTime: "05:00 AM" },
      { name: "Karimganj", arrivalTime: "06:30 AM", departureTime: "06:45 AM" },
      { name: "Lumding", arrivalTime: "09:00 AM", departureTime: "09:15 AM" },
      { name: "Howrah", arrivalTime: "01:00 PM", departureTime: "01:15 PM" },
      { name: "Chennai", arrivalTime: "11:00 PM", departureTime: "11:00 PM" },
    ],
    duration: "18h 0m",
  },
  {
    trainNumber: "14567",
    trainName: "Agartala-Kolkata Mail",
    from: "Agartala",
    to: "Kolkata",
    departureTime: "10:00 PM",
    arrivalTime: "01:00 PM",
    stops: [
      { name: "Agartala", arrivalTime: "10:00 PM", departureTime: "10:00 PM" },
      { name: "Dharmanagar", arrivalTime: "11:00 PM", departureTime: "11:15 PM" },
      { name: "Guwahati", arrivalTime: "06:00 AM", departureTime: "06:15 AM" },
      { name: "New Jalpaiguri", arrivalTime: "09:00 AM", departureTime: "09:15 AM" },
      { name: "Kolkata", arrivalTime: "01:00 PM", departureTime: "01:00 PM" },
    ],
    duration: "15h 0m",
  },
  {
    trainNumber: "15567",
    trainName: "Agartala-Delhi Express",
    from: "Agartala",
    to: "Delhi",
    departureTime: "06:00 AM",
    arrivalTime: "11:00 PM",
    stops: [
      { name: "Agartala", arrivalTime: "06:00 AM", departureTime: "06:00 AM" },
      { name: "Lumding", arrivalTime: "09:00 AM", departureTime: "09:15 AM" },
      { name: "New Jalpaiguri", arrivalTime: "01:00 PM", departureTime: "01:15 PM" },
      { name: "Patna", arrivalTime: "08:00 PM", departureTime: "08:15 PM" },
      { name: "Delhi", arrivalTime: "11:00 PM", departureTime: "11:00 PM" },
    ],
    duration: "17h 0m",
  },
  {
    trainNumber: "16789",
    trainName: "Agartala-Silchar Intercity",
    from: "Agartala",
    to: "Silchar",
    departureTime: "07:00 AM",
    arrivalTime: "11:00 AM",
    stops: [
      { name: "Agartala", arrivalTime: "07:00 AM", departureTime: "07:00 AM" },
      { name: "Dharmanagar", arrivalTime: "08:00 AM", departureTime: "08:15 AM" },
      { name: "Karimganj", arrivalTime: "09:30 AM", departureTime: "09:45 AM" },
      { name: "Silchar", arrivalTime: "11:00 AM", departureTime: "11:00 AM" },
    ],
    duration: "4h 0m",
  },
  {
    trainNumber: "17790",
    trainName: "Agartala-Jammu Tawi Express",
    from: "Agartala",
    to: "Jammu Tawi",
    departureTime: "05:30 AM",
    arrivalTime: "11:00 PM",
    stops: [
      { name: "Agartala", arrivalTime: "05:30 AM", departureTime: "05:30 AM" },
      { name: "Guwahati", arrivalTime: "08:00 AM", departureTime: "08:15 AM" },
      { name: "New Jalpaiguri", arrivalTime: "11:00 AM", departureTime: "11:15 AM" },
      { name: "Amritsar", arrivalTime: "07:00 PM", departureTime: "07:15 PM" },
      { name: "Jammu Tawi", arrivalTime: "11:00 PM", departureTime: "11:00 PM" },
    ],
    duration: "17h 30m",
  },

];
